DELIMITER $$

DROP FUNCTION IF EXISTS `IGNORE_PREFIXZERO`$$
CREATE FUNCTION  `IGNORE_PREFIXZERO`( str text ) RETURNS text CHARSET latin1
BEGIN
  RETURN trim(leading '0' from str);
END;

 $$

DELIMITER ;