DELIMITER $$

DROP PROCEDURE IF EXISTS `pr_run_previewreport` $$
CREATE PROCEDURE `pr_run_previewreport`(
  in in_recon_code varchar(32),
  in in_job_gid int,
  in in_rptsession_gid int,
  in in_user_code varchar(32),
  out out_msg text,
  out out_result int
)
me:BEGIN
  declare v_sql text default '';
  declare v_condition text default '';

	declare v_tran_table text default '';
	declare v_tranbrkp_table text default '';

  declare v_concurrent_ko_flag text default '';

  declare err_msg text default '';
  declare err_flag varchar(10) default false;

  -- concurrent KO flag
  set v_concurrent_ko_flag = fn_get_configvalue('concurrent_ko_flag');

  if v_concurrent_ko_flag = 'Y' then
	  set v_tran_table = concat(in_recon_code,'_tran');
	  set v_tranbrkp_table = concat(in_recon_code,'_tranbrkp');
  else
	  set v_tran_table = 'recon_trn_ttran';
	  set v_tranbrkp_table = 'recon_trn_ttranbrkp';
  end if;

  set in_job_gid = ifnull(in_job_gid,0);
  set in_rptsession_gid = ifnull(in_rptsession_gid,0);
  set in_user_code = ifnull(in_user_code,'');

  set v_condition = concat(' and a.job_gid = ',cast(in_job_gid as nchar),' ');
  set v_condition = concat(v_condition,' and a.rptsession_gid = ',cast(in_rptsession_gid as nchar),' ');

  set v_sql = concat(v_sql,"insert into recon_rpt_tpreview
		select
		  ",cast(in_rptsession_gid as nchar)," as rptsession_gid,
		  ",cast(in_job_gid as nchar)," as job_gid,
      a.preview_gid,
		  b.previewdtl_gid,
		  '",in_user_code,"' as user_code,
		  b.tran_gid,
		  b.tranbrkp_gid,
      a.preview_date,
		  a.preview_value,
		  a.recon_code,
		  d.recon_name,
		  a.rule_code,
		  e.rule_name,
		  a.reversal_flag,
		  b.src_comp_flag,
		  if(b.tranbrkp_gid > 0,'S','T') as rec_type,
      c.dataset_code,
      f.dataset_name,
		  c.tran_date,
		  c.tran_acc_mode,
		  c.tran_value,
		  c.excp_value,
      c.mapped_value,
      c.roundoff_value,
      0,
      0,
      '',
		  if(b.tran_mult = -1,b.excp_value,0) as value_debit,
		  if(b.tran_mult = 1,b.excp_value,0) as value_credit,
			c.col1,
			c.col2,
			c.col3,
			c.col4,
			c.col5,
			c.col6,
			c.col7,
			c.col8,
			c.col9,
			c.col10,
			c.col11,
			c.col12,
			c.col13,
			c.col14,
			c.col15,
			c.col16,
			c.col17,
			c.col18,
			c.col19,
			c.col20,
			c.col21,
			c.col22,
			c.col23,
			c.col24,
			c.col25,
			c.col26,
			c.col27,
			c.col28,
			c.col29,
			c.col30,
			c.col31,
			c.col32,
			c.col33,
			c.col34,
			c.col35,
			c.col36,
			c.col37,
			c.col38,
			c.col39,
			c.col40,
			c.col41,
			c.col42,
			c.col43,
			c.col44,
			c.col45,
			c.col46,
			c.col47,
			c.col48,
			c.col49,
			c.col50,
			c.col51,
			c.col52,
			c.col53,
			c.col54,
			c.col55,
			c.col56,
			c.col57,
			c.col58,
			c.col59,
			c.col60,
			c.col61,
			c.col62,
			c.col63,
			c.col64,
			c.col65,
			c.col66,
			c.col67,
			c.col68,
			c.col69,
			c.col70,
			c.col71,
			c.col72,
			c.col73,
			c.col74,
			c.col75,
			c.col76,
			c.col77,
			c.col78,
			c.col79,
			c.col80,
			c.col81,
			c.col82,
			c.col83,
			c.col84,
			c.col85,
			c.col86,
			c.col87,
			c.col88,
			c.col89,
			c.col90,
			c.col91,
			c.col92,
			c.col93,
			c.col94,
			c.col95,
			c.col96,
			c.col97,
			c.col98,
			c.col99,
			c.col100,
			c.col101,
			c.col102,
			c.col103,
			c.col104,
			c.col105,
			c.col106,
			c.col107,
			c.col108,
			c.col109,
			c.col110,
			c.col111,
			c.col112,
			c.col113,
			c.col114,
			c.col115,
			c.col116,
			c.col117,
			c.col118,
			c.col119,
			c.col120,
			c.col121,
			c.col122,
			c.col123,
			c.col124,
			c.col125,
			c.col126,
			c.col127,
			c.col128,
		  c.tran_remark1,
		  c.tran_remark2
		from recon_trn_tpreview as a
		inner join recon_trn_tpreviewdtl as b on a.preview_gid = b.preview_gid and a.job_gid = b.job_gid and b.tranbrkp_gid = 0 and b.delete_flag = 'N'
		inner join ",v_tran_table," as c on b.tran_gid = c.tran_gid and c.delete_flag = 'N'
		inner join recon_mst_trecon as d on a.recon_code = d.recon_code and d.delete_flag = 'N'
		left join recon_mst_trule as e on a.rule_code = e.rule_code and e.delete_flag = 'N'
    left join recon_mst_tdataset as f on c.dataset_code = f.dataset_code and f.delete_flag = 'N'
		where true ", v_condition,"

    union

		select
		  ",cast(in_rptsession_gid as nchar)," as rptsession_gid,
		  ",cast(in_job_gid as nchar)," as job_gid,
      a.preview_gid,
		  b.previewdtl_gid,
		  '",in_user_code,"' as user_code,
		  b.tran_gid,
		  b.tranbrkp_gid,
      a.preview_date,
		  a.preview_value,
		  a.recon_code,
		  d.recon_name,
		  a.rule_code,
		  e.rule_name,
		  a.reversal_flag,
		  b.src_comp_flag,
		  if(b.tranbrkp_gid > 0,'S','T') as rec_type,
      c.tranbrkp_dataset_code,
      f.dataset_name,
		  c.tran_date,
		  c.tran_acc_mode,
		  c.tran_value,
		  c.excp_value,
      0,
      0,
      g.tran_value,
      g.excp_value,
      g.tran_acc_mode,
		  if(b.tran_mult = -1,b.excp_value,0) as value_debit,
		  if(b.tran_mult = 1,b.excp_value,0) as value_credit,
			c.col1,
			c.col2,
			c.col3,
			c.col4,
			c.col5,
			c.col6,
			c.col7,
			c.col8,
			c.col9,
			c.col10,
			c.col11,
			c.col12,
			c.col13,
			c.col14,
			c.col15,
			c.col16,
			c.col17,
			c.col18,
			c.col19,
			c.col20,
			c.col21,
			c.col22,
			c.col23,
			c.col24,
			c.col25,
			c.col26,
			c.col27,
			c.col28,
			c.col29,
			c.col30,
			c.col31,
			c.col32,
			c.col33,
			c.col34,
			c.col35,
			c.col36,
			c.col37,
			c.col38,
			c.col39,
			c.col40,
			c.col41,
			c.col42,
			c.col43,
			c.col44,
			c.col45,
			c.col46,
			c.col47,
			c.col48,
			c.col49,
			c.col50,
			c.col51,
			c.col52,
			c.col53,
			c.col54,
			c.col55,
			c.col56,
			c.col57,
			c.col58,
			c.col59,
			c.col60,
			c.col61,
			c.col62,
			c.col63,
			c.col64,
			c.col65,
			c.col66,
			c.col67,
			c.col68,
			c.col69,
			c.col70,
			c.col71,
			c.col72,
			c.col73,
			c.col74,
			c.col75,
			c.col76,
			c.col77,
			c.col78,
			c.col79,
			c.col80,
			c.col81,
			c.col82,
			c.col83,
			c.col84,
			c.col85,
			c.col86,
			c.col87,
			c.col88,
			c.col89,
			c.col90,
			c.col91,
			c.col92,
			c.col93,
			c.col94,
			c.col95,
			c.col96,
			c.col97,
			c.col98,
			c.col99,
			c.col100,
			c.col101,
			c.col102,
			c.col103,
			c.col104,
			c.col105,
			c.col106,
			c.col107,
			c.col108,
			c.col109,
			c.col110,
			c.col111,
			c.col112,
			c.col113,
			c.col114,
			c.col115,
			c.col116,
			c.col117,
			c.col118,
			c.col119,
			c.col120,
			c.col121,
			c.col122,
			c.col123,
			c.col124,
			c.col125,
			c.col126,
			c.col127,
			c.col128,
		  '' as tran_remark1,
		  '' as tran_remark2
		from recon_trn_tpreview as a
		inner join recon_trn_tpreviewdtl as b on a.preview_gid = b.preview_gid and a.job_gid = b.job_gid and b.delete_flag = 'N'
		inner join ",v_tranbrkp_table," as c on b.tranbrkp_gid = c.tranbrkp_gid and c.delete_flag = 'N'
		inner join recon_mst_trecon as d on a.recon_code = d.recon_code and d.delete_flag = 'N'
		left join recon_mst_trule as e on a.rule_code = e.rule_code and e.delete_flag = 'N'
    left join recon_mst_tdataset as f on c.tranbrkp_dataset_code = f.dataset_code and f.delete_flag = 'N'
    left join ",v_tran_table," as g on c.tran_gid = g.tran_gid and c.delete_flag = 'N'
		where true ", v_condition," and b.tranbrkp_gid > 0
  ");

  call pr_run_sql(v_sql,@msg,@result);

  set out_msg = 'Success';
  set out_result = 1;
end $$

DELIMITER ;